name: Rancher Redeploy Action
description: >
  Redeploy a Rancher workload
inputs:
  mmx_binary:
    description: 'Mmx Api Key'
    required: true
  backend:
    description: 'Rancher backend'
    required: true
  access_key:
    description: 'Rancher Access Key'
    required: true
  secret_key:
    description: 'Rancher Secret Key'
    required: true
  project:
    description: 'Rancher Project'
    required: true
  namespace:
    description: 'Rancher Namespace'
    required: true
  workload:
    description: 'Rancher Workload'
    required: true
runs:
  using: 'docker'
  image: 'docker://registry.cn-shanghai.aliyuncs.com/mmx233/rancher_redeploy_action:latest'