name: Rancher Redeploy Action
description: >
  Redeploy a Rancher workload
inputs:
  backend:
    description: 'Rancher backend'
    required: true
  token:
    description: 'Rancher Bearer Token'
    required: true
  project:
    description: 'Rancher Project'
    required: true
  namespace:
    description: 'Rancher Namespace'
    required: true
  workload:
    description: 'Rancher Workload'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'